// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dao

import (
	"xyu-graphql/internal/dao/model"
)

type BookMutationObject struct {
	CreateBook *model.Book `json:"createBook"`
	DeleteBook *bool       `json:"deleteBook,omitempty"`
}

type BookQueryObject struct {
	Books       []*model.Book `json:"books"`
	GetBookByID []*model.Book `json:"getBookByID"`
}

type TodoMutationObject struct {
	NewTodo *model.Todo `json:"newTodo"`
}

type TodoQueryObject struct {
	Todos []*model.Todo `json:"todos"`
}
