// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

type AuthorType struct {
	Name *string `json:"name,omitempty"`
}

type Book struct {
	ID     int64   `json:"id"`
	Name   string  `json:"name"`
	Author *Author `json:"author"`
	UUID   string  `json:"uuid"`
}

type BookID struct {
	ID int64 `json:"id"`
}

type NewBook struct {
	Name   string      `json:"name"`
	Author *AuthorType `json:"author,omitempty"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
